### ISSUE TITLE
Time is off by an hour when copying google calendar event

### ISSUE THREAD

**Issue by joncfoo** [soupi/gathering#4]
Hi, I was attending the following event and turned up an hour late due to an off by one error :D - https://gathering.purescript.org/event/17

My time zone settings for google calendar (US/Mountain):
![image](https://user-images.githubusercontent.com/193628/33799962-bb38223a-dcf3-11e7-81fe-fffa12ff63ed.png)

I noticed the event is displayed in Central time (which is odd but fine) - notice that is is 15:00 here.
![image](https://user-images.githubusercontent.com/193628/33799951-874f69d8-dcf3-11e7-9e1a-e9d6e1352d75.png)

Clicking "copy to my calendar" brings up the event which is off by an hour - 16:00 in Central time - it should be 15:00 Central time.
![image](https://user-images.githubusercontent.com/193628/33799955-9f128924-dcf3-11e7-9ddd-08037b723e24.png)

I'm not sure where the error lies - google calendar or gathering.  Just thought I should let you know.

Thanks!

**Comment by soupi** [comment]
the google calendar event is actually not part of gathering but rather what the admin posted. 
pinging @chexxor which might have a better answer than I.

**Comment by chexxor** [comment]
Here's the event's configuration in Google Calendar (the event time zone is "(GMT-08:00) Pacific Time"):

![image](https://user-images.githubusercontent.com/843161/33800387-95a7eefe-dd04-11e7-8c07-26793be91b73.png)

It looks like the calendar on which that event is defined is "(GMT-06:00) Central Time", however:

![image](https://user-images.githubusercontent.com/843161/33800432-397afa4e-dd05-11e7-9537-3650d9aad2a5.png)

I wonder if the problem is there is two ways of adding the event to one's Google Calendar account:
1) subscribing to the event's calendar
2) copying the event to your own calendar

The interesting thing is that a Pacific Time person and a Central Time person said it was appropriately placed. I'm not sure what to change. This leads me to suspect that the problem is how a person added the event to their Google Calendar account. @joncfoo, what are your thoughts on this guess?

**Comment by chexxor** [comment]
I subscribed to the event's calendar, then changed my time zone from Central Time to Pacific Time, and the event's time adjusts from 3pm to 1pm, which is correct. So my guess that this was the problem is incorrect. We need to find another explanation for your problem.

**Comment by joncfoo** [comment]
@chexxor yea I think the issue I'm seeing arises with:

> 2. copying the event to your own calendar

When I click "copy to my calendar" the event is copied with an hour increase (see screenshots).  Do you see the same off-by-one error when you click "copy to my calendar"?

**Comment by chexxor** [comment]
@joncfoo I don't. I click "copy to my calendar" and I believe it adjusts to be correct with my account's time zone.

**Comment by joncfoo** [comment]
I can't explain why I see the hour increase - I signed out & in, tried a new browser and the same issue happens (hour increase when I copy event to my calendar).

But...when I switch over to the "new" calendar design the hour is no longer increased...yay?

![image](https://user-images.githubusercontent.com/193628/33801110-639885be-dd0d-11e7-973a-cb0c7f2248c6.png)

I guess we can mark this closed - this appears to be a bug in google's "old" calendar design.

Thanks for taking a look - I really appreciate it!

**Comment by chexxor** [comment]
Oh interesting - it must have been a bug in their app. :-/
Nice find! Thanks for upgrading your app UI to discover this answer, @joncfoo!

**Comment by soupi** [comment]
I'm glad this is resolved.
